const errors = {
    signUp186: "No userPool",
    signUp211: "The first parameter should either be non-null string or object",
    signUp214: "Username cannot be empty",
    signUp215: "Password cannot be empty",
    confirmSignUp242: "No userPool",
    confirmSignUp243: "Username cannot be empty",
    confirmSignUp244: "Code cannot be empty",
    resendSignUp263: "No userPool",
    resendSignUp264: "Username cannot be empty",
    signIn281: "No userPool",
    signIn282: "Username cannot be empty",
    setPreferredMFA447: "no validmfa method provided",
    confirmSignIn575: "Code cannot be empty",
    completeNewPassword609: "Password cannot be empty",
    sendCustomChallengeAnswer655: "No userPool",
    sendCustomChallengeAnswer656: "Challenge response cannot be empty",
    currentUserPoolUser739: "No userPool",
    currentUserPoolUser745: "No current user in userPool",
    currentUserPoolUser754: "No current user in userPool",
    getSyncedUser771: "No userPool",
    currentAuthenticatedUser800: "not authenticated",
    currentSession822: "No userPool",
    currentSession827: "No current user",
    currentSession835: "No current user",
    verifyUserAttributeSubmit949: "Code cannot be empty",
    forgotPassword1048: "No userPool",
    forgotPassword1049: "Username cannot be empty",
    forgotPasswordSubmit1078: "No userPool",
    forgotPasswordSubmit1079: "Username cannot be empty",
    forgotPasswordSubmit1080: "Code cannot be empty",
    forgotPasswordSubmit1081: "Password cannot be empty"
};
