const errors = {
    calculate177AuthenticationHelper: "Illegal paramater. A mod N cannot be 0.",
    getPasswordAuthenticationKey247AuthenticationHelper: "B cannot be zero.",
    getPasswordAuthenticationKey253AuthenticationHelper: "U cannot be zero.",
    bnpFromString192BigInteger: "Only radix 2, 4, 8, 16, 32 are supported",
    bnToString231BigInteger: "Only radix 2, 4, 8, 16, 32 are supported",
    fetch49Client: "Network error",
    fetch85Client: "Unknown error, the response body from fetch is: + responseJsonData",
    constructor84CognitoUser: "Username and pool information are required.",
    authenticateUser203CognitoUser: "Authentication flow type is invalid.",
    authenticateUserPlainUsernamePassword364CognitoUser: "PASSWORD parameter is required",
    completeNewPasswordChallenge529CognitoUser: "New password is required.",
    changePassword849CognitoUser: "User is not authenticated",
    enableMFA872CognitoUser: "User is not authenticated",
    setUserMfaPreference903CognitoUser: "User is not authenticated",
    disableMFA926CognitoUser: "User is not authenticated",
    deleteUser951CognitoUser: "User is not authenticated",
    updateAttributes977CognitoUser: "User is not authenticated",
    getUserAttributes999CognitoUser: "User is not authenticated",
    getMFAOptions1032CognitoUser: "User is not authenticated",
    getUserData1054CognitoUser: "User is not authenticated",
    deleteAttributes1077CognitoUser: "User is not authenticated",
    getSession1120CognitoUser: "Username is null. Cannot retrieve a new session",
    getSession1158CognitoUser: "Cannot retrieve a new session. Please authenticate.",
    getSession1163CognitoUser: "Local storage is missing an ID Token, Please authenticate",
    getAttributeVerificationCode1385CognitoUser: "User is not authenticated",
    verifyAttribute1414CognitoUser: "User is not authenticated",
    getDevice1439CognitoUser: "User is not authenticated",
    forgetSpecificDevice1464CognitoUser: "User is not authenticated",
    setDeviceStatusRemembered1508CognitoUser: "User is not authenticated",
    setDeviceStatusNotRemembered1533CognitoUser: "User is not authenticated",
    listDevices1561CognitoUser: "User is not authenticated",
    globalSignOut1586CognitoUser: "User is not authenticated",
    constructor38CognitoUserPool: "Both UserPoolId and ClientId are required.",
    constructor41CognitoUserPool: "Invalid UserPoolId format.",
    constructor29CognitoUserSession: "Id token and Access Token must be present."
};
